const indexR = require("./index");
const Q1R = require("./Q1");
const Q2R = require("./Q2");
const Q3R = require("./Q3");
const Q4R = require("./Q4");
const Q5R = require("./Q5");
const Q6R = require("./Q6");
const Q7R = require("./Q7");
const Q8R = require("./Q8");
const Q9R = require("./Q9");
const Q10R = require("./Q10");
const Q11R = require("./Q11");
const Q12R = require("./Q12");
const Q13R = require("./Q13");
const Q14R = require("./Q14");
const Q15R = require("./Q15");
const Q16R = require("./Q16");
const Q17R = require("./Q17");
const Q18R = require("./Q18");
const Q19R = require("./Q19");
const Q20R = require("./Q20");

exports.routesInit = (app) => {
    app.use("/", indexR);
    app.use("/", Q1R);
    app.use("/", Q2R);
    app.use("/", Q3R);
    app.use("/", Q4R);
    app.use("/", Q5R);
    app.use("/", Q6R);
    app.use("/", Q7R);
    app.use("/", Q8R);
    app.use("/", Q9R);
    app.use("/", Q10R);
    app.use("/", Q11R);
    app.use("/", Q12R);
    app.use("/", Q13R);
    app.use("/", Q14R);
    app.use("/", Q15R);
    app.use("/", Q16R);
    app.use("/", Q17R);
    app.use("/", Q18R);
    app.use("/", Q19R);
    app.use("/", Q20R);
};